version: '3.8'

services:
    webflux-db:
        image: postgres:13.1-alpine
        container_name: webflux-db
        ports:
            - 5435:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: db
        restart: always